export const actionTypes = {
    FECTHING_START: "FECTHING_START",
    FECTHING_SUCESS: "FECTHING_SUCESS",
    FECTHING_ERROR: "FECTHING_ERROR",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ITEMS: "REMOVE_ITEMS"
}